name: CI

concurrency:
  group: '${{ github.workflow }}-${{ github.head_ref || github.ref }}'
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  test:
    name: Test (Node ${{ matrix.node }})
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        node:
          - 20
          - 22
          - 24

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install Dependencies
        uses: marcalexiei/github-actions/.github/actions/setup-node-and-pnpm@main
        with:
          node-version: ${{ matrix.node }}

      - name: Build
        run: pnpm run build

      - name: Run test
        run: pnpm run test

  code-checks:
    name: Code checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install Dependencies
        uses: marcalexiei/github-actions/.github/actions/setup-node-and-pnpm@main

      - name: Run format
        run: pnpm run format

      - name: Build
        run: pnpm run build

      - name: Run test
        run: pnpm run lint

  ci-ok:
    name: CI OK
    runs-on: ubuntu-latest
    if: always()
    needs:
      - test
      - code-checks
    steps:
      - name: Exit with error if some jobs are not successful
        run: exit 1
        if: ${{ always() && (contains(needs.*.result, 'failure') || contains(needs.*.result, 'skipped') || contains(needs.*.result, 'cancelled')) }}
