name: Release

on:
  workflow_run:
    workflows: [CI]
    types: [completed]
    branches: [main]

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions: {}

env:
  HUSKY: 0

jobs:
  release:
    name: Release
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write
      id-token: write # Required for OIDC (Trusted publishing)

    steps:
      - name: Setup release helper
        id: release-helper
        uses: marcalexiei/github-actions/.github/actions/setup-github-app-user-bot@main
        with:
          app-id: ${{ vars.RELEASE_HELPER_APP_ID }}
          private-key: ${{ secrets.RELEASE_HELPER_PRIVATE_KEY }}

      - name: Configure git user for GitHub App
        run: |
          git config --global user.name '${{ steps.release-helper.outputs.bot-name }}'
          git config --global user.email '${{ steps.release-helper.outputs.bot-email }}'

      - name: Checkout
        uses: actions/checkout@v5
        with:
          persist-credentials: false

      - name: Install Dependencies
        uses: marcalexiei/github-actions/.github/actions/setup-node-and-pnpm@main

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          commit: 'chore: release'
          title: 'chore: release'
          publish: 'pnpm release'
          setupGitUser: false
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}

  on-ci-fail:
    name: 'Failure'
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'CI failed. Release won't be executed'
