name: Release

on:
  workflow_run:
    workflows:
      - CI
    types:
      - completed
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions: {}

env:
  HUSKY: 0

jobs:
  release:
    name: Release
    environment: release-npm
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write
      id-token: write # Required for OIDC (Trusted publishing)

    steps:
      - name: Setup release helper
        id: release-helper
        uses: marcalexiei/github-actions/setup-github-app-user-bot@e3b04865510c657477cc722854b31a3b74c72c09 # v2.2.0
        with:
          app-id: ${{ vars.RELEASE_HELPER_APP_ID }}
          private-key: ${{ secrets.RELEASE_HELPER_PRIVATE_KEY }}

      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Install Dependencies
        uses: marcalexiei/github-actions/setup-node-and-pnpm@e3b04865510c657477cc722854b31a3b74c72c09 # v2.2.0

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@22ccf9aa43179fe9e27dc62e575971d28cce197c # v2.0.0
        with:
          github-token: ${{ steps.release-helper.outputs.token }}
          commit-message: 'chore: release'
          pr-title: 'chore: release'
          pr-base-branch: main
          publish-script: 'pnpm release'

  on-ci-fail:
    name: 'Failure'
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'CI failed. Release won't be executed'
