name: Release

on:
  workflow_run:
    workflows:
      - CI
    types:
      - completed
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions: {}

env:
  HUSKY: 0

jobs:
  release:
    name: Release
    environment: release-npm
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write
      id-token: write # Required for OIDC (Trusted publishing)

    steps:
      - name: Setup release helper
        id: release-helper
        uses: marcalexiei/github-actions/.github/actions/setup-github-app-user-bot@f492a5a5b202006248f179569f7a1c2d4a2e1e13 # 1.3.0
        with:
          app-id: ${{ vars.RELEASE_HELPER_APP_ID }}
          private-key: ${{ secrets.RELEASE_HELPER_PRIVATE_KEY }}

      - name: Configure git user for GitHub App
        run: |
          git config --global user.name '${{ steps.release-helper.outputs.bot-name }}'
          git config --global user.email '${{ steps.release-helper.outputs.bot-email }}'

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Install Dependencies
        uses: marcalexiei/github-actions/.github/actions/setup-node-and-pnpm@f492a5a5b202006248f179569f7a1c2d4a2e1e13 # 1.3.0

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@63a615b9cd06ba9a3e6d13796c7fbcb080a60a0b # v1.8.0
        with:
          commit: 'chore: release'
          title: 'chore: release'
          publish: 'pnpm release'
          setupGitUser: false
        env:
          GITHUB_TOKEN: ${{ steps.release-helper.outputs.token }}

  on-ci-fail:
    name: 'Failure'
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'CI failed. Release won't be executed'
